version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - daveio
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    assignees:
      - daveio
