[env]
MOVIETOOL_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'

[tools]
python = { version = '3.13.3' }

[tasks]
'sync' = { run = 'uv sync' }
'dev' = { run = 'uv run start.py' }
'start' = { depends = ['sync', 'dev'] }
